#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:import WipeTransition kivy.uix.screenmanager.WipeTransition
#: import FadeTransition kivy.uix.screenmanager.FadeTransition
#: import translate __utils.translate
#: import date datetime
#: import timedelta datetime

ScreenManager:
    id: managescreen
    transition : SlideTransition(duration=.50)
    Screen:
        id : login
        name: 'Login'

        Screen:
            Image:
                source: "images/bg_login.jpg"
                pos_hint: {"center_x":0.2, "center_y":0.5}
                elevation: 1

            Image:
                source: "images/logo1.png"
                pos_hint: {"center_x":0.25, "center_y":0.5}
                size_hint_x: "0.4"
                size_hint_y: "0.4"
                elevation: 12

            Image:
                source: "images/logo.png"
                pos_hint: {"center_x":0.75, "center_y":0.8}
                size_hint_x: "0.3"
                size_hint_y: "0.3"
                elevation: 12

            MDTextField:
                id : username
                hint_text: translate('Username')
                pos_hint: {"center_x":0.76, "center_y":0.55}
                size_hint: 0.35, 0.11
                icon_right: "account"
                icon_right_color: 0.8, 0.8, 0.8, 1
                font_name: 'fonts/PS.ttf'

            MDTextField:
                id : password
                hint_text: translate('Password')
                password: True
                pos_hint: {"center_x":0.76, "center_y":0.40}
                size_hint: 0.35, 0.11
                icon_right: "lock"
                icon_right_color: 0.8, 0.8, 0.8, 1
                font_name: 'fonts/PS.ttf'

            MDFillRoundFlatIconButton:
                on_release : app.loadConnection()
                text: translate('Se_connecter')
                font_size: '16sp'
                bold: True  
                pos_hint: {"center_x":0.75, "center_y":0.25}
                size_hint: 0.15, 0.06
                elevation: 11
                icon: "arrow-right"
                id: button_login

            MDSpinner:
                id : loader
                color: 1,1,1,1
                size_hint: None, None
                size: dp(20), dp(20)
                pos_hint: {'center_x':0.75, 'center_y':0.25}
                active: False

            MDLabel:
                text: translate('errormdp')
                theme_text_color: "Custom"
                text_color: 0.3, 0.3, 0.3, 1
                font_name: 'fonts/PS.ttf'
                font_size: '13sp'
                bold: True
                pos_hint: {"center_x":1.08, "center_y":0.19}

            MDLabel:
                id: errorLogin
                text: ""
                theme_text_color: "Custom"
                text_color: get_color_from_hex("#fc0345")
                font_name: 'fonts/PS.ttf'
                font_size: '16sp'
                bold: True
                pos_hint: {"center_x":1.14, "center_y":0.15}

            MDLabel:
                text: "F-Society Copyright 2020"
                theme_text_color: "Custom"
                text_color: 0.3, 0.3, 0.3, 1
                font_name: 'fonts/PS.ttf'
                font_size: '12sp'
                bold: False
                pos_hint: {"center_x":1.18, "center_y":0.05}
            
    Screen:
        id : Main
        name: 'Main'
        Screen:
            NavigationLayout:
                ScreenManager:
                    Screen:
                        
                        ScreenManager:
                            id: mng
                            Screen:
                                name: "sc1"
                                Image:
                                    source: "images/cuisine.jpg"
                                    pos_hint: {"center_x":0.5, "center_y":0.75}
                                    size_hint_x: "1"
                                    size_hint_y: "0.8"
                                    elevation: 12
                                MDLabel:
                                    text: translate("CUISINE")
                                    pos_hint: {"center_x":1.1, "center_y":0.74}
                                    theme_text_color: "Custom"
                                    text_color: get_color_from_hex("#ffffff")
                                    font_name: 'fonts/PS.ttf'
                                    font_style: 'H3'
                                    bold: True
                                MDFillRoundFlatIconButton:
                                    text: translate("Tour_cuisine")
                                    font_size: '16sp'
                                    pos_hint: {"center_x":0.40, "center_y":0.59}
                                    size_hint: 0.18, 0.06
                                    elevation: 11
                                    icon: "sync"
                                    on_release : Tab_cuisine.current = 'Tour_cuisine'
                                MDFillRoundFlatIconButton:
                                    text: translate("Menu_repas")
                                    font_size: '16sp'
                                    pos_hint: {"center_x":0.68, "center_y":0.59}
                                    size_hint: 0.18, 0.06
                                    elevation: 11
                                    icon: "food"
                                    on_release : Tab_cuisine.current = 'Menu_cuisine'
                                ScreenManager:
                                    id : Tab_cuisine
                                    Screen:
                                        name:"Tour_cuisine"
                                        MDIconButton:
                                            icon: "chevron-left"
                                            pos_hint: {"center_x": 0.1, "center_y": 0.28}
                                            on_release : 
                                                cookSlide.current = 'slide1'
                                                cookSlide.transition = SlideTransition(direction='left')
                                        MDIconButton:
                                            icon: "chevron-right"
                                            pos_hint: {"center_x": 0.975, "center_y": 0.28}
                                            on_release : 
                                                cookSlide.current = 'slide2'
                                                cookSlide.transition = SlideTransition(direction='right')
                                        ScreenManager:
                                            id : cookSlide
                                            Screen:
                                                name:"slide1"
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.255, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Hier")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:                                                        
                                                        Image:
                                                            source: "images/food2.png"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "chef-hat"
                                                        text: app.tour_de_tache("hier","ck",1)
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: app.jour_de_tache("hier",1)
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.54, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Aujourd_hui")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:                                                                                                               
                                                        Image:
                                                            source: "images/food2.png"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "chef-hat"
                                                        text: app.tour_de_tache("aujourdhui","ck",1)
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: app.jour_de_tache("aujourdhui",1)
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.82, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Demain")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:                                                                                                               
                                                        Image:
                                                            source: "images/food2.png"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "chef-hat"
                                                        text: app.tour_de_tache("demain","ck",1)
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel: 
                                                        text: app.jour_de_tache("demain",1)
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'

                                            Screen:
                                                name : "slide2"
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.255, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Hier")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:                                                                                                               
                                                        Image:
                                                            source: "images/food2.png"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "chef-hat"
                                                        text: app.tour_de_tache("hier","ck",2)
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: app.jour_de_tache("hier",2)
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.54, "center_y": 0.28}
                                                    MDLabel:
                                                        text: "Aujourd'hui"
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:                                                                                                                
                                                        Image:
                                                            source: "images/food2.png"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "chef-hat"
                                                        text: app.tour_de_tache("aujourdhui","ck",2)
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: app.jour_de_tache("aujourdhui",2)
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.82, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Demain")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:                                                                                   
                                                        Image:
                                                            source: "images/food2.png"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "chef-hat"
                                                        text: app.tour_de_tache("demain","ck",2)
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: app.jour_de_tache("demain",2)
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                    Screen:
                                        name:"Menu_cuisine"
                                        MDLabel:
                                            text: translate("Semaine")
                                            pos_hint : {"center_x":0.715, "center_y":0.49}
                                            font_size: "14sp"
                                            font_style: "Subtitle2"

                                        AnchorLayout:
                                            pos_hint: {"center_x":0.535, "center_y":0.29}
                                            anchor_x: 'center'
                                            id: tableau_repas

                                        MDFillRoundFlatIconButton:
                                            pos_hint : {"center_x":0.535, "center_y":0.07}
                                            size_hint: 0.15, 0.06
                                            text: translate("Semaine_A")
                                            icon: "chevron-right"
                                            font_size: "16sp"
                            Screen:
                                name: "sc2"
                                Image:
                                    source: "images/menage.jpg"
                                    pos_hint: {"center_x":0.5, "center_y":0.75}
                                    size_hint_x: "1"
                                    size_hint_y: "0.8"
                                    elevation: 12
                                MDLabel:
                                    text: translate("MENAGE")
                                    pos_hint: {"center_x":1.1, "center_y":0.74}
                                    theme_text_color: "Custom"
                                    text_color: get_color_from_hex("#ffffff")
                                    font_name: 'fonts/PS.ttf'
                                    font_style: 'H3'
                                    bold: True
                                MDFillRoundFlatIconButton:
                                    text: translate("Tour_menage")
                                    font_size: '16sp'
                                    pos_hint: {"center_x":0.21, "center_y":0.59}
                                    size_hint: 0.18, 0.06
                                    elevation: 11
                                    icon: "sync"
                                    on_release : Tab_menage.current = 'Tour_menage'
                                MDFillRoundFlatIconButton:
                                    text: translate("Autre_menage")
                                    font_size: '16sp'
                                    pos_hint: {"center_x":0.43, "center_y":0.59}
                                    size_hint: 0.18, 0.06
                                    elevation: 11
                                    icon: "sync"
                                    on_release : Tab_menage.current = 'Autre_menage'
                                MDFillRoundFlatIconButton:
                                    text: translate("Grand_menage")
                                    font_size: '16sp'
                                    pos_hint: {"center_x":0.65, "center_y":0.59}
                                    size_hint: 0.18, 0.06
                                    elevation: 11
                                    icon: "broom"
                                    on_release : Tab_menage.current = 'Grand_menage'
                                MDFillRoundFlatIconButton:
                                    text: "Ordures"
                                    font_size: '16sp'
                                    pos_hint: {"center_x":0.87, "center_y":0.59}
                                    size_hint: 0.18, 0.06
                                    elevation: 11
                                    icon: "trash-can"
                                    on_release : Tab_menage.current = 'ordure'

                                ScreenManager:
                                    id : Tab_menage
                                    Screen:
                                        name: "Tour_menage"
                                        MDIconButton:
                                            icon: "chevron-left"
                                            pos_hint: {"center_x": 0.1, "center_y": 0.28}
                                            on_release : 
                                                menageSlide.current = 'slide1_men'
                                                menageSlide.transition = SlideTransition(direction='left')
                                        MDIconButton:
                                            icon: "chevron-right"
                                            pos_hint: {"center_x": 0.975, "center_y": 0.28}
                                            on_release : 
                                                menageSlide.current = 'slide2_men'
                                                menageSlide.transition = SlideTransition(direction='right')
                                        ScreenManager:
                                            id : menageSlide
                                            Screen:
                                                name:"slide1_men"
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.255, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Hier")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:                                                       
                                                        Image:
                                                            source: "images/broom1.jpg"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12
                                                    MDRoundFlatIconButton:
                                                        icon: "broom"
                                                        text: "Arleme"
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: "14-11-20"
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.54, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Aujourd_hui")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:                                                        
                                                        Image:
                                                            source: "images/broom1.jpg"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "broom"
                                                        text: "Dinahasina"
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: "14-11-20"
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.82, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Demain")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:                                                       
                                                        Image:
                                                            source: "images/broom1.jpg"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "broom"
                                                        text: "Sarino"
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: "15-11-20"
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                            Screen:
                                                name : "slide2_men"
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.255, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Hier")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:                 
                                                        Image:
                                                            source: "images/broom1.jpg"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "broom"
                                                        text: "Aina"
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: "14-11-20"
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.54, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Aujourd_hui")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:                                                       
                                                        Image:
                                                            source: "images/broom1.jpg"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "broom"
                                                        text: "Landry"
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: "14-11-20"
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.82, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Demain")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:                                                       
                                                        Image:
                                                            source: "images/broom1.jpg"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "broom"
                                                        text: "Gaetan"
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: "15-11-20"
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                    Screen:
                                        name:"Autre_menage"
                                        MDIconButton:
                                            icon: "chevron-left"
                                            pos_hint: {"center_x": 0.1, "center_y": 0.28}
                                            on_release : 
                                                autre_menageSlide.current = 'slide1_autre_men'
                                                autre_menageSlide.transition = SlideTransition(direction='left')
                                        MDIconButton:
                                            icon: "chevron-right"
                                            pos_hint: {"center_x": 0.975, "center_y": 0.28}
                                            on_release : 
                                                autre_menageSlide.current = 'slide2_autre_men'
                                                autre_menageSlide.transition = SlideTransition(direction='right')
                                        ScreenManager:
                                            id : autre_menageSlide
                                            Screen:
                                                name:"slide1_autre_men"
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.255, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Hier")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:
                                                        Image:
                                                            source: "images/broom.jpg"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "broom"
                                                        text: "Haja"
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: "14-11-20"
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.54, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Aujourd_hui")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:
                                                        Image:
                                                            source: "images/broom.jpg"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "broom"
                                                        text: "Landry"
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: "14-11-20"
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.82, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Demain")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:
                                                        Image:
                                                            source: "images/broom.jpg"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "broom"
                                                        text: "Casimir"
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: "15-11-20"
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                            Screen:
                                                name:"slide2_autre_men"
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.255, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Hier")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:
                                                        Image:
                                                            source: "images/broom.jpg"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "broom"
                                                        text: "Fabien"
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: "14-11-20"
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.54, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Aujourd_hui")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:
                                                        Image:
                                                            source: "images/broom.jpg"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "broom"
                                                        text: "Landry"
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: "14-11-20"
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                                MDCard:
                                                    orientation: "vertical"
                                                    padding: "15dp"
                                                    size_hint: None, None
                                                    size: "250dp", "220dp"
                                                    pos_hint: {"center_x": 0.82, "center_y": 0.28}
                                                    MDLabel:
                                                        text: translate("Demain")
                                                        font_name: 'fonts/PS.ttf'
                                                        font_style: 'Subtitle2'
                                                        theme_text_color: "Custom"
                                                        text_color: get_color_from_hex("#FF5722")
                                                        size_hint_y: None
                                                        height: self.texture_size[1]
                                                    MDSeparator:
                                                        height: "2dp"
                                                    MDBoxLayout:
                                                        Image:
                                                            source: "images/broom.jpg"
                                                            pos_hint: {"center_x":0.5, "center_y":0.5}
                                                            size_hint_x: "1"
                                                            size_hint_y: "0.8"
                                                            elevation: 12   
                                                    MDRoundFlatIconButton:
                                                        icon: "broom"
                                                        text: "Aina"
                                                        pos_hint: {"center_x":0.5, "center_y":0.5}
                                                        font_name: 'fonts/PS.ttf'
                                                        font_size: '20sp'
                                                    MDLabel:
                                                        text: "15-11-20"
                                                        pos_hint: {"x":0.38, "y":0.75}
                                                        font_name: 'fonts/PS.ttf'
                                    Screen:
                                        name:"Grand_menage"
                                        MDRaisedButton:
                                            id : raisedBtn1
                                            text: "VITRES"
                                            pos_hint: {"center_x":0.18, "center_y":0.47}
                                            font_size: '15sp'
                                            size_hint: 0.17, 0.06
                                            md_bg_color: 1, 0, 1, 1
                                        MDRaisedButton:
                                            id : raisedBtn2
                                            text: "Landry"
                                            pos_hint: {"center_x":0.18, "center_y":0.192}
                                            font_size: '15sp'
                                            size_hint: 0.17, 0.06
                                            
                                        MDFloatingActionButton:
                                            icon: "trash-can"
                                            pos_hint: {"center_x":0.16, "center_y":0.10}
                                            user_font_size: "15sp"
                                            theme_text_color: "Custom"
                                            text_color: get_color_from_hex("#ffffff")
                                            md_bg_color: get_color_from_hex("#f04d4d")
                                            elevation_normal: 0
                                            on_release : app.show_init_dialog(2)
                                        MDFloatingActionButton:
                                            id : edit1
                                            icon: "pencil"
                                            pos_hint: {"center_x":0.205, "center_y":0.10}
                                            user_font_size: "15sp"
                                            theme_text_color: "Custom"
                                            text_color: get_color_from_hex("#ffffff")
                                            md_bg_color: get_color_from_hex("#4df070")
                                            elevation_normal: 0
                                            on_release: app.show_edit_dialog(2)
                                        Image:
                                            source: "images/vitre2.jpg"
                                            pos_hint: {"center_x":0.18, "center_y":0.33}
                                            size_hint_x: "0.23"
                                            size_hint_y: "0.23"
                                        MDRaisedButton:
                                            id : raisedBtn3
                                            text: "DOUCHE ET WC"
                                            pos_hint: {"center_x":0.36, "center_y":0.47}
                                            font_size: '15sp'
                                            size_hint: 0.17, 0.06
                                        MDRaisedButton:
                                            id : raisedBtn4
                                            text: "Dinahasina-Sarino"
                                            pos_hint: {"center_x":0.36, "center_y":0.192}
                                            font_size: '15sp'
                                            size_hint: 0.17, 0.06
                                            color:1,1,1,1
                                        MDFloatingActionButton:
                                            icon: "trash-can"
                                            pos_hint: {"center_x":0.34, "center_y":0.10}
                                            user_font_size: "15sp"
                                            theme_text_color: "Custom"
                                            text_color: get_color_from_hex("#ffffff")
                                            md_bg_color: get_color_from_hex("#f04d4d")
                                            elevation_normal: 0
                                            on_release : app.show_init_dialog(4)
                                        MDFloatingActionButton:
                                            id : edit2
                                            icon: "pencil"
                                            pos_hint: {"center_x":0.385, "center_y":0.10}
                                            user_font_size: "15sp"
                                            theme_text_color: "Custom"
                                            text_color: get_color_from_hex("#ffffff")
                                            md_bg_color: get_color_from_hex("#4df070")
                                            elevation_normal: 0
                                            on_release: app.show_edit_dialog(4)
                                        Image:
                                            source: "images/wc2.jpg"
                                            pos_hint: {"center_x":0.36, "center_y":0.33}
                                            size_hint_x: "0.23"
                                            size_hint_y: "0.23"
                                        MDRaisedButton:
                                            id : raisedBtn5
                                            text: "SALLE INFO"
                                            pos_hint: {"center_x":0.54, "center_y":0.47}
                                            font_size: '15sp'
                                            size_hint: 0.17, 0.06
                                        MDRaisedButton:
                                            id : raisedBtn6
                                            text: "Casimir-Arleme"
                                            pos_hint: {"center_x":0.54, "center_y":0.192}
                                            font_size: '15sp'
                                            size_hint: 0.17, 0.06
                                        MDFloatingActionButton:
                                            icon: "trash-can"
                                            pos_hint: {"center_x":0.52, "center_y":0.10}
                                            user_font_size: "15sp"
                                            theme_text_color: "Custom"
                                            text_color: get_color_from_hex("#ffffff")
                                            md_bg_color: get_color_from_hex("#f04d4d")
                                            elevation_normal: 0
                                            on_release : app.show_init_dialog(6)
                                        MDFloatingActionButton:
                                            id : edit3
                                            icon: "pencil"
                                            pos_hint: {"center_x":0.565, "center_y":0.10}
                                            user_font_size: "15sp"
                                            theme_text_color: "Custom"
                                            text_color: get_color_from_hex("#ffffff")
                                            md_bg_color: get_color_from_hex("#4df070")
                                            elevation_normal: 0
                                            on_release: app.show_edit_dialog(6)
                                        Image:
                                            source: "images/vitre2.jpg"
                                            pos_hint: {"center_x":0.54, "center_y":0.33}
                                            size_hint_x: "0.23"
                                            size_hint_y: "0.23"
                                        MDRaisedButton:
                                            id : raisedBtn7
                                            text: "USTENSILS"
                                            pos_hint: {"center_x":0.72, "center_y":0.47}
                                            font_size: '15sp'
                                            size_hint: 0.17, 0.06
                                        MDRaisedButton:
                                            id : raisedBtn8
                                            text: "Aina-Haja"
                                            pos_hint: {"center_x":0.72, "center_y":0.192}
                                            font_size: '15sp'
                                            size_hint: 0.17, 0.06
                                        MDFloatingActionButton:
                                            icon: "trash-can"
                                            pos_hint: {"center_x":0.70, "center_y":0.10}
                                            user_font_size: "15sp"
                                            theme_text_color: "Custom"
                                            text_color: get_color_from_hex("#ffffff")
                                            md_bg_color: get_color_from_hex("#f04d4d")
                                            elevation_normal: 0
                                            on_release : app.show_init_dialog(8)
                                        MDFloatingActionButton:
                                            id : edit4
                                            icon: "pencil"
                                            pos_hint: {"center_x":0.745, "center_y":0.10}
                                            user_font_size: "15sp"
                                            theme_text_color: "Custom"
                                            text_color: get_color_from_hex("#ffffff")
                                            md_bg_color: get_color_from_hex("#4df070")
                                            elevation_normal: 0
                                            on_release: app.show_edit_dialog(8)
                                        Image:
                                            source: "images/ustencils.jpg"
                                            pos_hint: {"center_x":0.72, "center_y":0.33}
                                            size_hint_x: "0.23"
                                            size_hint_y: "0.23"
                                        MDRaisedButton:
                                            id : raisedBtn9
                                            text: "SOLS"
                                            pos_hint: {"center_x":0.90, "center_y":0.47}
                                            font_size: '15sp'
                                            size_hint: 0.17, 0.06
                                        MDRaisedButton:
                                            id : raisedBtn10
                                            text: "Gaetan-Fabien"
                                            pos_hint: {"center_x":0.90, "center_y":0.192}
                                            font_size: '15sp'
                                            size_hint: 0.17, 0.06
                                        MDFloatingActionButton:
                                            icon: "trash-can"
                                            pos_hint: {"center_x":0.88, "center_y":0.10}
                                            user_font_size: "15sp"
                                            theme_text_color: "Custom"
                                            text_color: get_color_from_hex("#ffffff")
                                            md_bg_color: get_color_from_hex("#f04d4d")
                                            elevation_normal: 0
                                            on_release : app.show_init_dialog(10)
                                        MDFloatingActionButton:
                                            id : edit5
                                            icon: "pencil"
                                            pos_hint: {"center_x":0.925, "center_y":0.10}
                                            user_font_size: "15sp"
                                            theme_text_color: "Custom"
                                            text_color: get_color_from_hex("#ffffff")
                                            md_bg_color: get_color_from_hex("#4df070")
                                            elevation_normal: 0
                                            on_release: app.show_edit_dialog(10)
                                        Image:
                                            source: "images/sol2.png"
                                            pos_hint: {"center_x":0.90, "center_y":0.33}
                                            size_hint_x: "0.23"
                                            size_hint_y: "0.23"
                                        
                                        
                                       
                                                                                
                                    Screen:
                                        name:"ordure"
                                        MDCard:
                                            orientation: "vertical"
                                            padding: "15dp"
                                            size_hint: None, None
                                            size: "160dp", "220dp"
                                            pos_hint: {"center_x": 0.18, "center_y": 0.28}
                                            Image:
                                                source: "images/trash.png"
                                                pos_hint: {"center_x":0.5, "center_y":0.75}
                                                size_hint_x: "1"
                                                size_hint_y: "3.5"
                                                elevation: 12   
                                            MDLabel:
                                                text: "Aina"
                                                pos_hint: {"x":0.38, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                            MDLabel:
                                                text: "Landry"
                                                pos_hint: {"x":0.32, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                        MDCard:
                                            orientation: "vertical"
                                            padding: "15dp"
                                            size_hint: None, None
                                            size: "160dp", "220dp"
                                            pos_hint: {"center_x": 0.36, "center_y": 0.28}
                                            Image:
                                                source: "images/trash.png"
                                                pos_hint: {"center_x":0.5, "center_y":0.75}
                                                size_hint_x: "1"
                                                size_hint_y: "3.5"
                                                elevation: 12   
                                            MDLabel:
                                                text: "Zacké"
                                                pos_hint: {"x":0.33, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                            MDLabel:
                                                text: "Arleme"
                                                pos_hint: {"x":0.31, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                        MDCard:
                                            orientation: "vertical"
                                            padding: "15dp"
                                            size_hint: None, None
                                            size: "160dp", "265dp"
                                            pos_hint: {"center_x": 0.54, "center_y": 0.28}
                                            MDIconButton:
                                                icon: "star"
                                                theme_text_color: "Custom"
                                            Image:
                                                source: "images/trash.png"
                                                pos_hint: {"center_x":0.5, "center_y":0.75}
                                                size_hint_x: "1"
                                                size_hint_y: "3.5"
                                                elevation: 12   
                                            MDLabel:
                                                text: "Haja"
                                                pos_hint: {"x":0.38, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                            MDLabel:
                                                text: "Sarino"
                                                pos_hint: {"x":0.32, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                            MDSwitch:
                                                pos_hint: {'center_x': .47, 'center_y': .5}
                                        MDCard:
                                            orientation: "vertical"
                                            padding: "15dp"
                                            size_hint: None, None
                                            size: "160dp", "220dp"
                                            pos_hint: {"center_x": 0.72, "center_y": 0.28}
                                            MDIconButton:
                                                icon: "star"
                                                theme_text_color: "Custom"
                                            Image:
                                                source: "images/trash.png"
                                                pos_hint: {"center_x":0.5, "center_y":0.75}
                                                size_hint_x: "1"
                                                size_hint_y: "3.5"
                                                elevation: 12   
                                            MDLabel:
                                                text: "Gaetan"
                                                pos_hint: {"x":0.29, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                            MDLabel:
                                                text: "Dinahasina"
                                                pos_hint: {"x":0.20, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                        MDCard:
                                            orientation: "vertical"
                                            padding: "15dp"
                                            size_hint: None, None
                                            size: "160dp", "220dp"
                                            pos_hint: {"center_x": 0.90, "center_y": 0.28}
                                            Image:
                                                source: "images/trash.png"
                                                pos_hint: {"center_x":0.5, "center_y":0.75}
                                                size_hint_x: "1"
                                                size_hint_y: "3.5"
                                                elevation: 12   
                                            MDLabel:
                                                text: "Fabien"
                                                pos_hint: {"x":0.30, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                            MDLabel:
                                                text: "Casimir"
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                                pos_hint: {"x":0.30, "y":0.75}
                                            

                            Screen:
                                name: "sc3"
                                Image:
                                    source: "images/argent.jpg"
                                    pos_hint: {"center_x":0.5, "center_y":0.75}
                                    size_hint_x: "1"
                                    size_hint_y: "0.8"
                                    elevation: 12
                                MDLabel:
                                    text: translate("ARGENT")
                                    pos_hint: {"center_x":1.1, "center_y":0.74}
                                    theme_text_color: "Custom"
                                    text_color: get_color_from_hex("#ffffff")
                                    font_name: 'fonts/PS.ttf'
                                    font_style: 'H3'
                                    bold: True
                                MDFillRoundFlatIconButton:
                                    text: "Cotisations"
                                    font_size: '16sp'
                                    pos_hint: {"center_x":0.40, "center_y":0.59}
                                    size_hint: 0.18, 0.06
                                    elevation: 11
                                    icon: "currency-eur"
                                    on_release : Tab_argent.current = 'Cotisation'
                                MDFillRoundFlatIconButton:
                                    text: "Historiques"
                                    font_size: '16sp'
                                    pos_hint: {"center_x":0.68, "center_y":0.59}
                                    size_hint: 0.18, 0.06
                                    elevation: 11
                                    icon: "chart-bar"
                                    on_release : Tab_argent.current = 'Historique'
                                ScreenManager:
                                    id : Tab_argent
                                    Screen:
                                        id : Cotisation
                                        name: "Cotisation"
                                        MDLabel:
                                            text: "Ces cotisations concerne ce mois en cours, il faut payer avant le 20 de ce mois"
                                            pos_hint : {"center_x":0.786, "center_y":0.52}
                                            font_size: "14sp"
                                            font_style: "Subtitle2"
                                        MDCard:
                                            orientation: "vertical"
                                            padding: "15dp"
                                            size_hint: None, None
                                            size: "180dp", "220dp"
                                            pos_hint: {"center_x": 0.30, "center_y": 0.31}
                                            MDFloatingActionButton:
                                                icon: "check-bold"
                                                user_font_size: "14sp"
                                                theme_text_color: "Custom"
                                                text_color: get_color_from_hex("#ffffff")
                                                md_bg_color: get_color_from_hex("#04bf4c")
                                                elevation_normal: 0
                                            MDLabel:
                                                text: "Bazar"
                                                pos_hint: {"x":0.36, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                            MDRoundFlatIconButton:
                                                icon: "currency-eur"
                                                text: "15000 Ar"
                                                pos_hint: {"center_x":0.5, "center_y":0.5}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '15sp'
                                                margin: "30dp"
                                            MDIconButton:
                                                icon: "trash-can"
                                                theme_text_color: "Custom"
                                                font_size: "18sp"
                                                text_color: get_color_from_hex("#071f38")
                                                pos_hint: {"center_x":0.5, "center_y":0.3}
                                        MDCard:
                                            orientation: "vertical"
                                            padding: "15dp"
                                            size_hint: None, None
                                            size: "180dp", "220dp"
                                            pos_hint: {"center_x": 0.55, "center_y": 0.31}
                                            MDFloatingActionButton:
                                                icon: "alert"
                                                user_font_size: "14sp"
                                                theme_text_color: "Custom"
                                                text_color: get_color_from_hex("#ffffff")
                                                md_bg_color: get_color_from_hex("#faaf00")
                                                elevation_normal: 0
                                            MDLabel:
                                                text: "Tee-shirt"
                                                pos_hint: {"x":0.30, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                            MDRoundFlatIconButton:
                                                icon: "currency-eur"
                                                text: "15000 Ar"
                                                pos_hint: {"center_x":0.5, "center_y":0.5}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '15sp'
                                            MDIconButton:
                                                icon: "trash-can"
                                                theme_text_color: "Custom"
                                                font_size: "18sp"
                                                text_color: get_color_from_hex("#071f38")
                                                pos_hint: {"center_x":0.5, "center_y":0.3}       
                                        
                                        MDSeparator:
                                            height: "4dp"    
                                            pos_hint: {"center_x":0.5, "center_y":0.11}      
                                        MDLabel:
                                            text: "Cette section est réservée à l'admin spécifique:"
                                            pos_hint : {"center_x":0.64, "center_y":0.05}
                                            font_size: "14sp"
                                            font_style: "Subtitle2"
                                        MDFillRoundFlatIconButton:
                                            text: "Ajouter une cotisation"
                                            font_size: '16sp'
                                            pos_hint: {"center_x":0.56, "center_y":0.05}
                                            size_hint: 0.22, 0.06
                                            elevation: 11
                                            icon: "card-plus-outline"
                                            on_press: app.add_cotis_dialog()
                                        MDFillRoundFlatIconButton:
                                            text: "Payer"
                                            font_size: '16sp'
                                            pos_hint: {"center_x":0.74, "center_y":0.05}
                                            size_hint: 0.12, 0.06
                                            elevation: 11
                                            icon: "cash-plus"
                                            on_press : app.paye_cotisation()
                                        MDFillRoundFlatIconButton:
                                            text: "Retirer"
                                            font_size: '16sp'
                                            pos_hint: {"center_x":0.87, "center_y":0.05}
                                            size_hint: 0.12, 0.06
                                            elevation: 11
                                            icon: "cash-minus"                          
                                    Screen:
                                        name: "Historique"
                                        ScreenManager:
                                            id : tab_argent
                                            Screen:
                                                name:"tab_cotisation"
                                                MDLabel:
                                                    text: "Ci-dessous sont les status de payement des cotisations de ce mois en cours"
                                                    pos_hint : {"center_x":0.795, "center_y":0.54}
                                                    font_size: "14sp"
                                                    font_style: "Subtitle2"
                                                AnchorLayout:
                                                    pos_hint: {"center_x":0.50, "center_y":0.27}
                                                    anchor_x: 'center'
                                                    id: tableau_status_cotisation
                                                MDFloatingActionButton:
                                                    icon: "chevron-right"
                                                    user_font_size: "20sp"
                                                    theme_text_color: "Custom"
                                                    pos_hint: {"center_x":0.95, "center_y":0.27}
                                                    text_color: get_color_from_hex("#ffffff")
                                                    md_bg_color: get_color_from_hex("#071f38")
                                                    on_release : tab_argent.current = 'tab_transaction'
                                                    elevation_normal: 0
                                                
                                            Screen:
                                                name:"tab_transaction"
                                                MDLabel:
                                                    text: "Ci-dessous sont les transactions effectuées ce mois-ci"
                                                    pos_hint : {"center_x":0.87, "center_y":0.53}
                                                    font_size: "14sp"
                                                    font_style: "Subtitle2"
                                                AnchorLayout:
                                                    pos_hint: {"center_x":0.573, "center_y":0.27}
                                                    anchor_x: 'center'
                                                    id: tableau_transaction
                                                MDFloatingActionButton:
                                                    icon: "chevron-left"
                                                    user_font_size: "20sp"
                                                    theme_text_color: "Custom"
                                                    pos_hint: {"center_x":0.12, "center_y":0.27}
                                                    text_color: get_color_from_hex("#ffffff")
                                                    md_bg_color: get_color_from_hex("#071f38")
                                                    on_release : tab_argent.current = 'tab_cotisation'
                                                    elevation_normal: 0


                            Screen:
                                name: "sc4"
                                Image:
                                    source: "images/jirama.jpg"
                                    pos_hint: {"center_x":0.5, "center_y":0.75}
                                    size_hint_x: "1"
                                    size_hint_y: "0.8"
                                    elevation: 12
                                MDLabel:
                                    text: "JIRAMA"
                                    pos_hint: {"center_x":1.1, "center_y":0.74}
                                    theme_text_color: "Custom"
                                    text_color: get_color_from_hex("#ffffff")
                                    font_name: 'fonts/PS.ttf'
                                    font_style: 'H3'
                                    bold: True
                                MDFillRoundFlatIconButton:
                                    text: "Factures"
                                    font_size: '16sp'
                                    pos_hint: {"center_x":0.40, "center_y":0.59}
                                    size_hint: 0.18, 0.06
                                    elevation: 11
                                    icon: "card-text"
                                    on_release : Tab_jirama.current = 'facture'
                                MDFillRoundFlatIconButton:
                                    text: "Status"
                                    font_size: '16sp'
                                    pos_hint: {"center_x":0.68, "center_y":0.59}
                                    size_hint: 0.18, 0.06
                                    elevation: 11
                                    icon: "list-status"
                                    on_release : Tab_jirama.current = 'status'
                                ScreenManager:
                                    id : Tab_jirama
                                    Screen:
                                        name: "facture"
                                        MDLabel:
                                            text: "Ces factures concernent le ou les mois qui n'ont pas encore été payés"
                                            pos_hint : {"center_x":0.815, "center_y":0.52}
                                            font_size: "14sp"
                                            font_style: "Subtitle2"
                                        MDCard:
                                            orientation: "vertical"
                                            padding: "15dp"
                                            size_hint: None, None
                                            size: "180dp", "220dp"
                                            pos_hint: {"center_x": 0.30, "center_y": 0.31}
                                            MDFloatingActionButton:
                                                icon: "check-bold"
                                                user_font_size: "14sp"
                                                theme_text_color: "Custom"
                                                text_color: get_color_from_hex("#ffffff")
                                                md_bg_color: get_color_from_hex("#04bf4c")
                                                elevation_normal: 0
                                            MDLabel:
                                                text: "Septembre"
                                                pos_hint: {"x":0.25, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                            MDRoundFlatIconButton:
                                                icon: "currency-eur"
                                                text: "10000 Ar"
                                                pos_hint: {"center_x":0.5, "center_y":0.5}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '15sp'
                                                margin: "30dp"
                                            MDIconButton:
                                                icon: "trash-can"
                                                theme_text_color: "Custom"
                                                font_size: "18sp"
                                                text_color: get_color_from_hex("#071f38")
                                                pos_hint: {"center_x":0.5, "center_y":0.3}
                                        MDCard:
                                            orientation: "vertical"
                                            padding: "15dp"
                                            size_hint: None, None
                                            size: "180dp", "220dp"
                                            pos_hint: {"center_x": 0.55, "center_y": 0.31}
                                            MDFloatingActionButton:
                                                icon: "alert"
                                                user_font_size: "14sp"
                                                theme_text_color: "Custom"
                                                text_color: get_color_from_hex("#ffffff")
                                                md_bg_color: get_color_from_hex("#faaf00")
                                                elevation_normal: 0
                                            MDLabel:
                                                text: "Novembre"
                                                pos_hint: {"x":0.26, "y":0.75}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '18sp'
                                            MDRoundFlatIconButton:
                                                icon: "currency-eur"
                                                text: "9000 Ar"
                                                pos_hint: {"center_x":0.5, "center_y":0.5}
                                                font_name: 'fonts/PS.ttf'
                                                font_size: '15sp'
                                            MDIconButton:
                                                icon: "trash-can"
                                                theme_text_color: "Custom"
                                                font_size: "18sp"
                                                text_color: get_color_from_hex("#071f38")
                                                pos_hint: {"center_x":0.5, "center_y":0.3}       
                                        
                                        MDSeparator:
                                            height: "4dp"    
                                            pos_hint: {"center_x":0.5, "center_y":0.11}      
                                        MDLabel:
                                            text: "Cette section est réservée à l'admin spécifique:"
                                            pos_hint : {"center_x":0.70, "center_y":0.05}
                                            font_size: "14sp"
                                            font_style: "Subtitle2"
                                        MDFillRoundFlatIconButton:
                                            text: "Ajouter une facture"
                                            font_size: '16sp'
                                            pos_hint: {"center_x":0.63, "center_y":0.05}
                                            size_hint: 0.22, 0.06
                                            elevation: 11
                                            icon: "card-plus-outline"
                                        MDFillRoundFlatIconButton:
                                            text: "Payer"
                                            font_size: '16sp'
                                            pos_hint: {"center_x":0.81, "center_y":0.05}
                                            size_hint: 0.12, 0.06
                                            elevation: 11
                                            icon: "cash-plus"                        
                                    Screen:
                                        name: "status"
                                        MDLabel:
                                            text: "Ci-dessous sont les status de payement des factures"
                                            pos_hint : {"center_x":0.87, "center_y":0.54}
                                            font_size: "14sp"
                                            font_style: "Subtitle2"
                                        AnchorLayout:
                                            pos_hint: {"center_x":0.535, "center_y":0.27}
                                            anchor_x: 'center'
                                            id: tableau_status_facture
                            
                            
                            
                            
                            
                            
                            
                            Screen:
                                name: "sc5"
                                Image:
                                    source: "images/trosa.jpg"
                                    pos_hint: {"center_x":0.5, "center_y":0.75}
                                    size_hint_x: "1"
                                    size_hint_y: "0.8"
                                    elevation: 12
                                MDLabel:
                                    text: "TROSA"
                                    pos_hint: {"center_x":1.1, "center_y":0.74}
                                    theme_text_color: "Custom"
                                    text_color: get_color_from_hex("#ffffff")
                                    font_name: 'fonts/PS.ttf'
                                    font_style: 'H3'
                                    bold: True
                            Screen:
                                name: "sc6"
                                Image:
                                    source: "images/membre.jpg"
                                    pos_hint: {"center_x":0.5, "center_y":0.75}
                                    size_hint_x: "1"
                                    size_hint_y: "0.8"
                                    elevation: 12
                                MDLabel:
                                    text: translate("MEMBRES")
                                    pos_hint: {"center_x":1.1, "center_y":0.74}
                                    theme_text_color: "Custom"
                                    text_color: get_color_from_hex("#ffffff")
                                    font_name: 'fonts/PS.ttf'
                                    font_style: 'H3'
                                    bold: True
                        
                        
                        BoxLayout:
                            orientation: 'vertical'
                            
                            CustomToolbar:
                                id: toolbar
                                md_bg_color : get_color_from_hex("#ee4135")
                                size_hint_y: None
                                height: self.theme_cls.standard_increment
                                elevation: 10
                                pos_hint: {"top": 1}


                                MDFillRoundFlatIconButton:
                                    id: button_1
                                    icon: "home"
                                    text:"GFS"
                                    user_font_size: "100sp"
                                    pos_hint: {"center_y": .5}
                                   

                                Widget:

                                MDFillRoundFlatIconButton:
                                    id: button_2
                                    icon: "dots-vertical"
                                    text:"Arleme"
                                    pos_hint: {"center_x":.8, "center_y": .5}
                                    on_release: app.menu.open()

                                        
                            MDBoxLayout:
                                MDNavigationRail:
                                    id: rail
                                    md_bg_color: get_color_from_hex("#020d12")
                                    color_normal: get_color_from_hex("#7e8782")
                                    color_active: get_color_from_hex("#ffffff")
                                    visible: "Unlabeled"
                                    elevation:10
                                    hover_bg: 0, 0, 0, .2
                                    
                                    MDNavigationRailItem:
                                        icon: "food"
                                        text: translate("Cuisine")
                                        on_release:
                                            mng.current = "sc1"
                                    
                                    MDNavigationRailItem:
                                        icon: "broom"
                                        text: translate("Menage")
                                        on_release:
                                            mng.current = "sc2"
                                    
                                    MDNavigationRailItem:
                                        icon: "currency-eur"
                                        text: translate("Cotisation")
                                        on_release:
                                            mng.current = "sc3"
                                    
                                    MDNavigationRailItem:
                                        icon: "flash"
                                        text: "Jirama"
                                        on_release:
                                            mng.current = "sc4"
                                    
                                    MDNavigationRailItem:
                                        icon: "backup-restore"
                                        text: translate("Dette")
                                        on_release:
                                            mng.current = "sc5"
                                    
                                    MDNavigationRailItem:
                                        icon: "account-multiple"
                                        text: translate("Membres")
                                        on_release:
                                            mng.current = "sc6"